name: Daily Link Check
on:
  schedule:
    - cron: "0 14 * * *"
jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"
      - run: npm install
      - run: node url-checker/url-checker.js
